version: '3.8'

# ====================================== AIRFLOW COMMON ========================================

x-airflow-common: &airflow-common
  image: &airflow_image apache/airflow:2.2.2-python3.8
  environment: &airflow-common-env
    AIRFLOW__API__AUTH_BACKEND: airflow.api.auth.backend.basic_auth
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__CORE__LOAD_DEFAULT_CONNECTIONS: 'false'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql://airflow:airflow@postgres:5432/airflow
    AIRFLOW__CORE__STORE_DAG_CODE: 'true'
    AIRFLOW__CORE__STORE_SERIALIZED_DAGS: 'true'
    AIRFLOW__WEBSERVER__EXPOSE_CONFIG: 'true'
    MOVIELENS_USER: 'airflow'
    MOVIELENS_PASSWORD: 'airflow'
    MOVIELENS_HOST: 'http://movielens:5010'
  volumes:
    - ./dags:/opt/airflow/dags
    - logs:/opt/airflow/logs
  networks: &airflow-common-networks
    airflow:
  depends_on: &airflow-common-depends-on
    postgres:
      condition: service_healthy

x-vols-dags: &vols-dags
  "./dags:/opt/airflow/dags"

x-vols-logs: &vols-logs
  "logs:/opt/airflow/logs"

# ====================================== /AIRFLOW COMMON =======================================

services:
  postgres:
    image: postgres:14-alpine
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "airflow" ]
      interval: 5s
      retries: 5
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    networks:
      <<: *airflow-common-networks
    ports:
      - "5432:5432"

  init:
    build:
      context: airflow-docker
      args:
        AIRFLOW_BASE_IMAGE: *airflow_image
    image: airflowbook/airflow-ch10
    container_name: chapter10_airflow_init
    depends_on:
      <<: *airflow-common-depends-on
    networks:
      <<: *airflow-common-networks
    environment: *airflow-common-env
    entrypoint: /bin/bash
    command: -c 'airflow db init && airflow users create --username user --password password --firstname Marin --lastname Marin --role Admin --email admin@example.org'

  webserver:
    <<: *airflow-common
    build:
      context: airflow-docker
      args:
        AIRFLOW_BASE_IMAGE: *airflow_image
    image: airflowbook/airflow-ch10
    container_name: chapter10_airflow_webserver
    networks:
      <<: *airflow-common-networks
    command: webserver
    ports:
      - "8080:8080"
    healthcheck:
      test:  [ "CMD", "curl", "--fail", "http://localhost:8080/health" ]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      init:
        condition: service_completed_successfully

  scheduler:
    <<: *airflow-common
    build:
      context: airflow-docker
      args:
        AIRFLOW_BASE_IMAGE: *airflow_image
    image: airflowbook/airflow-ch10
    container_name: chapter10_airflow_scheduler
    networks:
      <<: *airflow-common-networks
    command: scheduler
    healthcheck:
      test: [ "CMD-SHELL", 'airflow jobs check --job-type SchedulerJob --hostname "$${HOSTNAME}"' ]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always
    volumes:
      - *vols-dags
      - *vols-logs
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      <<: *airflow-common-depends-on
      init:
        condition: service_completed_successfully

  movielens:
    build: ../chapter08/movielens-api
    image: airflow/movielens-api
    container_name: chapter10_movielens_api
    networks:
      <<: *airflow-common-networks
    ports:
      - "5010:5010"
    environment:
      API_USER: airflow
      API_PASSWORD: airflow

networks:
  airflow:
    name: airflow

volumes:
  logs:
    name: ch10_logs
