version: '3.8'

# ====================================== AIRFLOW COMMON ========================================

x-airflow-common: &airflow-common
  image: &airflow_image apache/airflow:2.2.4-python3.8
  environment: &airflow-common-env
    AIRFLOW__API__AUTH_BACKEND: airflow.api.auth.backend.basic_auth
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__CORE__LOAD_DEFAULT_CONNECTIONS: 'false'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql://airflow:airflow@postgres:5432/airflow
    AIRFLOW__CORE__STORE_DAG_CODE: 'true'
    AIRFLOW__CORE__STORE_SERIALIZED_DAGS: 'true'
    AIRFLOW__CORE__FERNET_KEY: EomypBljHcoY3zkxIznIgc5RNdnCjDB9WuHcLziXgu8=
    AIRFLOW__WEBSERVER__EXPOSE_CONFIG: 'true'
    # Movielens settings
    AIRFLOW_CONN_MOVIELENS: http://${MOVIELENS_USER}:${MOVIELENS_PASSWORD}@movielens-api
    # GCP setttings.
#    AIRFLOW_CONN_GCP: google-cloud-platform://user:password@?__extra__=
#    AIRFLOW_CONN_GCP: google-cloud-platform://user:password@?extra__google_cloud_platform__keyfile_dict=${GCP_KEY}'

  volumes:
    - ./dags:/opt/airflow/dags
    - logs:/opt/airflow/logs
  depends_on: &airflow-common-depends-on
    postgres:
      condition: service_healthy

x-vols-dags: &vols-dags
               "./dags:/opt/airflow/dags"

x-vols-logs: &vols-logs
               "logs:/opt/airflow/logs"

# ====================================== /AIRFLOW COMMON =======================================

services:
  postgres:
    image: postgres:14-alpine
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "airflow" ]
      interval: 5s
      retries: 5
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    ports:
      - "5432:5432"

  initdb:
    build:
      context: airflow-gcp
      args:
        AIRFLOW_BASE_IMAGE: *airflow_image
    image: airflow-ch18/airflow-gcp
    depends_on:
      *airflow-common-depends-on
    environment: *airflow-common-env
    entrypoint: /bin/bash
    command: -c 'airflow db init && airflow users create --username user --password password --firstname Marin --lastname Marin --role Admin --email admin@example.org'

  webserver:
    <<: *airflow-common
    build:
      context: airflow-gcp
      args:
        AIRFLOW_BASE_IMAGE: *airflow_image
    image: airflow-ch18/airflow-gcp
    command: webserver
    ports:
      - "8080:8080"
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:8080/health" ]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always
    env_file:
      - .env
    environment: *airflow-common-env
    volumes:
      - *vols-logs
    depends_on:
      <<: *airflow-common-depends-on
      initdb:
        condition: service_completed_successfully


  scheduler:
    <<: *airflow-common
    #    image: *airflow_image
    build:
      context: airflow-gcp
      args:
        AIRFLOW_BASE_IMAGE: *airflow_image
    image: airflow-ch18/airflow-gcp
    command: scheduler
    healthcheck:
      test: [ "CMD-SHELL", 'airflow jobs check --job-type SchedulerJob --hostname "$${HOSTNAME}"' ]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always
    env_file:
      - .env
    environment: *airflow-common-env
    volumes:
      - *vols-dags
      - *vols-logs
    depends_on:
      <<: *airflow-common-depends-on
      initdb:
        condition: service_completed_successfully

  # service taken from chapter08
  movielens-api:
    build: ../chapter08/movielens-api
    image: airflow/movielens-api
    ports:
      - "5010:5010"
    environment:
      API_USER: airflow
      API_PASSWORD: airflow

volumes:
  logs:
