# This is a basic workflow to help you get started with Actions

name: python static checks and tests

# Controls when the workflow will run
#on: [push]
on:
  push:
    branches:
      - chapter-09

      # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          architecture: x64

      - name: Install Flake8
        run: pip install flake8
      - name: Run Flake8
        run: flake8 --ignore=E501,W503,E203,E302

      # - name: Install Pylint
      #   run: pip install pylint
      # - name: Run Pylint
      #   run: find . -name "*.py" | xargs pylint --rcfile=.pylintrc

      - name: Install Black
        run: pip install black
      - name: Run Black
        run: find . -name "*.py" | xargs black --check

      - name: Install dependencies
        run: pip install apache-airflow pytest

      - name: Test DAG integrity
        run: pytest tests/
        env:
          working-directory: ./chapter09
